name: CI

on:
  push:
    branches:
      - canary

  pull_request:
    branches:
      - canary

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format-check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Test
        timeout-minutes: 30
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a npm test
          else
            npm test
          fi
        shell: bash
